### ISSUE TITLE
Notes from floating figures are ordered like in the source code

### ISSUE THREAD

**Issue by lluchs** [ntjess/typst-drafting#15] opened 2024-08-13 19:24 UTC
Example:

```typst
#import "@preview/drafting:0.2.0": margin-note, set-page-properties

#set-page-properties()

Some text.
#margin-note[note from text]

#figure(
  placement: top,
  caption: [Figure with note#margin-note[note from figure]],
  box(width: 100%, height: 5cm, stroke: 1pt + black)
)
```

![result](https://github.com/user-attachments/assets/60e90b03-5c09-4573-9430-99ae2411c692)

The note in the caption is placed correctly next to the figure if there is no other note on the page. With the note in the text, it is sorted like in the source code, thus appearing below the text note.

**Comment by ntjess** [comment] 2024-11-11 09:41
Notice how your figure placement is floating. If you remove `placement: top`, the note placement works more intuitively.

The position reported by a figure (`context here()`) is where it exists in the code (an invisible block _after_ the text), so the `margin-note` can only see this location.

I will close this as expected behavior, since `here()` doesn't distinguish the _actual_ placed location of floating content -- and therefore `margin-note` can't do anything to float the note alongside it. I agree though, it's not ideal...

**Closed by ntjess** 2024-11-11 09:41 UTC
